#LOG_FILE=/tmp/redis
#
#source common.sh
#

#echo "setup yum repo for redis"
#yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y &>>${LOG_FILE}
#StatusCheck $?
- name: Configure Redis YUM Repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes

#echo "enabling redis yum modules"
#dnf module enable redis:remi-6.2 -y &>>${LOG_FILE}
#StatusCheck $?
- name: install redis 6.2
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

#echo "installing redis"
#yum install redis -y &>>${LOG_FILE}
#StatusCheck $?
- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: installed
    disable_gpg_check: yes



#
#echo "update listener address"
#  #Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf & /etc/redis/redis.conf
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/redis.conf /etc/redis/redis.conf
#StatusCheck $?

- name: updating redis listener config
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf


#echo "enable redis"
#systemctl enable redis &>>${LOG_FILE}
#StatusCheck $?
#
#echo "starting redis"
#systemctl restart redis &>>${LOG_FILE}
#StatusCheck $?

- name: Start Redis Service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes