- name: Create Parameters in AWS
  hosts: localhost
  tasks:
    - name: Update a Parameter
      community.aws.ssm_parameter:
        name: "{{item.name}}"
        string_type: "String"
        value: "{{item.value}}"
        overwrite_value: "always"
      loop:
        - { name: "roboshop.dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.roboshop.internal:27017/catalogue" }