- name: Create Parameters in AWS
  hosts: localhost
  tasks:
    - name: Update a Parameter
      community.aws.ssm_parameter:
        name: "{{item.name}}"
        string_type: "String"
        value: "{{item.value}}"
        overwrite_value: "always"
      loop:
        - { name: "roboshop.dev.catalogue.MONGO _URL", value: "mongodb://mongodb-dev.roboshop.internal:27017/catalogue" }
        - { name: "roboshop.dev.cart.REDIS_HOST", value: "redis-dev.roboshop.internal" }
        - { name: "roboshop.dev.cart.CATALOGUE_HOST", value: "catalogue-dev.roboshop.internal" }
        - { name: "roboshop.dev.frontend.CATALOGUE_HOST", value: "catalogue-dev.roboshop.internal" }
        - { name: "roboshop.dev.frontend.CART_HOST", value: "cart-dev.roboshop.internal" }
        - { name: "roboshop.dev.frontend.USER_HOST", value: "user-dev.roboshop.internal" }
        - { name: "roboshop.dev.frontend.SHIPPING_HOST", value: "shipping-dev.roboshop.internal" }
        - { name: "roboshop.dev.frontend.PAYMENT_HOST", value: "payment-dev.roboshop.internal" }
        - { name: "roboshop.dev.payment.CART_HOST", value: "cart-dev.roboshop.internal" }
        - { name: "roboshop.dev.payment.USER_HOST", value: "user-dev.roboshop.internal" }
        - { name: "roboshop.dev.payment.AMQP_HOST", value: "rabbitmq-dev.roboshop.internal" }
        - { name: "roboshop.dev.payment.AMQP_HOST", value: "rabbitmq-dev.roboshop.internal" }
        - { name: "roboshop.dev.shipping.CART_ENDPOINT", value: "cart-dev.roboshop.internal" }
        - { name: "roboshop.dev.shipping.DB_HOST", value: "mysql-dev.roboshop.internal" }