- name: Copy Elastic Yum Repo File
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copy Filebeat Configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restart Service
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes